### PR TITLE
Bulma fixes

### PR DESCRIPTION
**Pull request by YashdalfTheGray**
* event delegation for the hamburger and the notification button
* fixed the flexbox classes to look for a class and not an element
* added some margin to the notification to make it look a little cleaner

### CODE REVIEW

**Comment by YashdalfTheGray** [comment]
Assuming that jQuery was only being used for that specific Javascript code that I changed to vanilla JS, I've also killed our dependency on jQuery :tada:

**Comment by YashdalfTheGray** [comment]
@mikestephens ☝️ does that hold true? Otherwise, I'll undelete the `require jquery` line.

**Comment by mikestephens** [comment]
The require jquery was just a leftover dep of bootstrap

**Comment by YashdalfTheGray** [comment]
Interesting fix.

**Pull request merged**
